In [23]:
import pandas as pd
import numpy as np

def magic(n):
  n = int(n)
  if n < 3:
    raise ValueError("Size must be at least 3")
  if n % 2 == 1:
    p = np.arange(1, n+1)
    return n*np.mod(p[:, None] + p - (n+3)//2, n) + np.mod(p[:, None] + 2*p-2, n) + 1
  elif n % 4 == 0:
    J = np.mod(np.arange(1, n+1), 4) // 2
    K = J[:, None] == J
    M = np.arange(1, n*n+1, n)[:, None] + np.arange(n)
    M[K] = n*n + 1 - M[K]
  else:
    p = n//2
    M = magic(p)
    M = np.block([[M, M+2*p*p], [M+3*p*p, M+p*p]])
    i = np.arange(p)
    k = (n-2)//4
    j = np.concatenate((np.arange(k), np.arange(n-k+1, n)))
    M[np.ix_(np.concatenate((i, i+p)), j)] = M[np.ix_(np.concatenate((i+p, i)), j)]
    M[np.ix_([k, k+p], [0, k])] = M[np.ix_([k+p, k], [0, k])]
  return M 

In [24]:
mat = magic(3)
display(mat)

array([[8, 1, 6],
       [3, 5, 7],
       [4, 9, 2]])

In [26]:
ltmat = np.tril(mat)
display(ltmat)

array([[8, 0, 0],
       [3, 5, 0],
       [4, 9, 2]])

In [27]:
# utmat = ltmat.T
utmat = np.triu(mat.T)
display(utmat)

array([[8, 3, 4],
       [0, 5, 9],
       [0, 0, 2]])